In [31]:
import plotly.express as px
import numpy as np
import pandas as pd
from itertools import product

#   Test of the basic strategy

In [32]:
df_modelisation = pd.read_csv("../data/modelisation.csv", index_col="datetime", parse_dates=["datetime"])

In [33]:
df_modelisation

,id_vwap_fr,da_actual_price,biomass_storm_fct,blast_gas_storm_fct,coal_storm_fct,free_fuel_storm_fct,hydro_storm_fct,nat_gas_storm_fct,nuclear_storm_fct,pump_storm_fct,...,pv_fr_fct,wind_fr_fct,da_storm_de_fct,da_storm_fr_fct,da_storm_be_fct,da_storm_ch_fct,da_storm_uk_fct,da_storm_es_fct,da_storm_it_fct,ID-DA
datetime,,,,,,,,,,,,,,,,,,,,,
2025-10-01 00:00:00+00:00,43.626318,47.572548,170.0,0.0,0.0,1300.0,4620.402611,244.965335,44796.900710,518.433885,...,0.0,3611.0,92.823599,62.781038,85.028114,95.667173,78.441648,92.428490,95.667173,-3.946230
2025-10-01 01:00:00+00:00,37.378636,29.470029,170.0,0.0,0.0,1300.0,4620.402611,244.965335,44786.018600,-680.510551,...,0.0,3294.0,93.399464,62.493387,85.403241,96.316262,76.966422,87.375832,97.026640,7.908606
2025-10-01 02:00:00+00:00,43.223529,44.027544,170.0,0.0,0.0,1300.0,4620.402611,244.965335,44786.018600,-1469.744516,...,0.0,3013.0,96.983280,55.194615,82.235118,97.240042,79.276055,94.154694,97.240042,-0.804015
2025-10-01 03:00:00+00:00,22.386379,28.802529,170.0,0.0,0.0,1300.0,4620.402611,244.965335,44786.018600,-828.138798,...,0.0,2802.0,105.824834,62.781038,79.786115,105.824834,76.233699,93.132527,105.824834,-6.416149
2025-10-01 04:00:00+00:00,57.228210,61.415061,170.0,0.0,0.0,1300.0,4620.402611,263.511636,44786.018600,229.762638,...,0.0,2659.0,134.953865,62.781038,94.882998,134.953865,65.698697,110.215819,131.043466,-4.186851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-26 20:00:00+00:00,105.611044,95.077500,170.0,0.0,0.0,1300.0,7449.206763,240.751931,43280.000000,3045.900000,...,0.0,5118.0,144.711742,32.614642,124.158429,108.684927,131.253301,101.234130,121.096683,10.533544
2026-04-26 21:00:00+00:00,82.049278,81.800000,170.0,0.0,0.0,1300.0,7452.460000,242.380951,43280.000000,3045.900000,...,0.0,5751.0,125.283802,32.614642,112.769416,102.000000,121.247111,97.443223,113.959096,0.249278
2026-04-26 22:00:00+00:00,53.990460,49.665000,170.0,0.0,0.0,1300.0,6683.980000,243.862991,43255.000000,1728.743655,...,0.0,5582.0,109.256805,15.148342,111.817103,109.256805,111.842891,58.086000,108.116691,4.325460
2026-04-26 23:00:00+00:00,27.250754,43.115000,170.0,0.0,0.0,1300.0,5862.035587,244.965335,43255.000000,1143.597716,...,0.0,4885.0,106.654451,15.148342,111.817103,106.654451,102.667583,58.086000,108.048916,-15.864246
2026-04-27 00:00:00+00:00,26.224625,40.620000,170.0,0.0,0.0,1300.0,5683.980000,244.965335,42999.591151,736.525872,...,0.0,3725.0,105.028539,22.017332,105.729429,105.028539,99.341224,59.257397,106.483916,-14.395375

In [34]:
df_p_n_v = pd.read_csv("../data/P_n_V.csv", index_col="datetime", parse_dates=["datetime"])
df_p_n_v = df_p_n_v.loc["2025-10-01 00:00:00+00:00":"2026-04-27 00:00:00+00:00"]
df_p_n_v

                             P_t  P_max
datetime
2025-10-01 00:00:00+00:00  87.56    9.0
2025-10-01 01:00:00+00:00  87.56    9.0
2025-10-01 02:00:00+00:00  87.56    9.0
2025-10-01 03:00:00+00:00  87.56    9.0
2025-10-01 04:00:00+00:00  87.56    9.0
...                          ...    ...
2026-04-26 20:00:00+00:00  29.96    9.0
2026-04-26 21:00:00+00:00  29.96    9.0
2026-04-26 22:00:00+00:00  29.96    9.0
2026-04-26 23:00:00+00:00  29.96    9.0
2026-04-27 00:00:00+00:00  29.96    9.0

[4993 rows x 2 columns]

In [35]:
df_basic_strat = df_modelisation.join(df_p_n_v, how='inner')
df_basic_strat

,id_vwap_fr,da_actual_price,biomass_storm_fct,blast_gas_storm_fct,coal_storm_fct,free_fuel_storm_fct,hydro_storm_fct,nat_gas_storm_fct,nuclear_storm_fct,pump_storm_fct,...,da_storm_de_fct,da_storm_fr_fct,da_storm_be_fct,da_storm_ch_fct,da_storm_uk_fct,da_storm_es_fct,da_storm_it_fct,ID-DA,P_t,P_max
datetime,,,,,,,,,,,,,,,,,,,,,
2025-10-01 00:00:00+00:00,43.626318,47.572548,170.0,0.0,0.0,1300.0,4620.402611,244.965335,44796.900710,518.433885,...,92.823599,62.781038,85.028114,95.667173,78.441648,92.428490,95.667173,-3.946230,87.56,9.0
2025-10-01 01:00:00+00:00,37.378636,29.470029,170.0,0.0,0.0,1300.0,4620.402611,244.965335,44786.018600,-680.510551,...,93.399464,62.493387,85.403241,96.316262,76.966422,87.375832,97.026640,7.908606,87.56,9.0
2025-10-01 02:00:00+00:00,43.223529,44.027544,170.0,0.0,0.0,1300.0,4620.402611,244.965335,44786.018600,-1469.744516,...,96.983280,55.194615,82.235118,97.240042,79.276055,94.154694,97.240042,-0.804015,87.56,9.0
2025-10-01 03:00:00+00:00,22.386379,28.802529,170.0,0.0,0.0,1300.0,4620.402611,244.965335,44786.018600,-828.138798,...,105.824834,62.781038,79.786115,105.824834,76.233699,93.132527,105.824834,-6.416149,87.56,9.0
2025-10-01 04:00:00+00:00,57.228210,61.415061,170.0,0.0,0.0,1300.0,4620.402611,263.511636,44786.018600,229.762638,...,134.953865,62.781038,94.882998,134.953865,65.698697,110.215819,131.043466,-4.186851,87.56,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-26 20:00:00+00:00,105.611044,95.077500,170.0,0.0,0.0,1300.0,7449.206763,240.751931,43280.000000,3045.900000,...,144.711742,32.614642,124.158429,108.684927,131.253301,101.234130,121.096683,10.533544,29.96,9.0
2026-04-26 21:00:00+00:00,82.049278,81.800000,170.0,0.0,0.0,1300.0,7452.460000,242.380951,43280.000000,3045.900000,...,125.283802,32.614642,112.769416,102.000000,121.247111,97.443223,113.959096,0.249278,29.96,9.0
2026-04-26 22:00:00+00:00,53.990460,49.665000,170.0,0.0,0.0,1300.0,6683.980000,243.862991,43255.000000,1728.743655,...,109.256805,15.148342,111.817103,109.256805,111.842891,58.086000,108.116691,4.325460,29.96,9.0
2026-04-26 23:00:00+00:00,27.250754,43.115000,170.0,0.0,0.0,1300.0,5862.035587,244.965335,43255.000000,1143.597716,...,106.654451,15.148342,111.817103,106.654451,102.667583,58.086000,108.048916,-15.864246,29.96,9.0
2026-04-27 00:00:00+00:00,26.224625,40.620000,170.0,0.0,0.0,1300.0,5683.980000,244.965335,42999.591151,736.525872,...,105.028539,22.017332,105.729429,105.028539,99.341224,59.257397,106.483916,-14.395375,29.96,9.0

In [36]:
# --- Train/Test split temporel sur df_basic_strat ---
df_basic_strat = df_basic_strat.sort_index()

df_train = df_basic_strat.loc[df_basic_strat.index < "2026-03-16 00:00:00+00:00"].copy()
df_test = df_basic_strat.loc[df_basic_strat.index >= "2026-03-16 00:00:00+00:00"].copy()

print("Train:", df_train.index.min(), "->", df_train.index.max(), f"({len(df_train)} lignes)")
print("Test :", df_test.index.min(), "->", df_test.index.max(), f"({len(df_test)} lignes)")

Train: 2025-10-01 00:00:00+00:00 -> 2026-03-15 23:00:00+00:00 (3984 lignes)
Test : 2026-03-16 00:00:00+00:00 -> 2026-04-27 00:00:00+00:00 (1009 lignes)

## PnL - ID premium strategy

Baseline: `V(t) = P_max` sold at price `P(t) = P_t`.

ID premium strategy: a share `id_factor` of the volume is valued with an
intraday premium, the remaining share `(1 - id_factor)` stays at price `P(t)`.

- `id_factor` in [0, p%], p = 20%
- `id_premium` = MAX (over the last `x` days, x = 2) of the average (ID3 - DA) per hour bucket
- `id_premium_min` = 0
- `id_premium` clipped to [id_premium_min, 400]

Similar hours (UTC): night 21-05, morning_peak 07-09, solar 10-16,
evening 18-20, shoulder (06 & 17).

In [37]:
#NEW

# ---------------------------------------------------------------------------
# Parameters
# ---------------------------------------------------------------------------
X_DAYS = 2
P_FACTOR = 0.20
PREMIUM_FLOOR = 0
PREMIUM_MAX = 400

ID_COL = "id_vwap_fr"
DA_COL = "da_actual_price"
VOL_COL = "P_max"
PRICE_COL = "P_t"

# France DA vs other countries (for the ID premium min)
FR_DA_COL = "da_storm_fr_fct"
OTHER_DA_COLS = [
    "da_storm_de_fct", "da_storm_be_fct", "da_storm_ch_fct",
    "da_storm_uk_fct", "da_storm_es_fct", "da_storm_it_fct"
]

DEFAULT_HOUR_TO_BUCKET = {
    21: "night", 22: "night", 23: "night", 0: "night", 1: "night", 2: "night", 3: "night", 4: "night", 5: "night",
    7: "morning_peak", 8: "morning_peak", 9: "morning_peak",
    10: "solar", 11: "solar", 12: "solar", 13: "solar", 14: "solar", 15: "solar", 16: "solar",
    18: "evening", 19: "evening", 20: "evening",
    6: "shoulder", 17: "shoulder",
}

def assign_hour_bucket(idx, hour_to_bucket=None):
    """Classify each timestamp into hour buckets."""
    mapping = DEFAULT_HOUR_TO_BUCKET if hour_to_bucket is None else hour_to_bucket
    h = pd.Series(idx.hour, index=idx)
    bucket = h.map(mapping).fillna("other")
    return pd.Series(bucket.values, index=idx, name="hour_bucket")

def build_hour_bucket_map(df_train, n_buckets, spread_col="ID-DA"):
    """
    Build hour->bucket map from train data only:
    group hours by similar mean spread (quantile buckets).
    """
    hourly_spread = df_train.groupby(df_train.index.hour)[spread_col].mean().reindex(range(24))
    if hourly_spread.isna().any():
        # fallback robuste si certaines heures manquent
        hourly_spread = hourly_spread.fillna(hourly_spread.mean())

    # rank -> unique ordering, then qcut into n_buckets groups
    ranked = hourly_spread.rank(method="first")
    labels = [f"bucket_{i}" for i in range(n_buckets)]
    bucket_labels = pd.qcut(ranked, q=n_buckets, labels=labels, duplicates="drop")

    return {int(h): str(bucket_labels.loc[h]) for h in bucket_labels.index}

def compute_pnl(
    df,
    x_days=X_DAYS,
    p_factor=P_FACTOR,
    premium_floor=PREMIUM_FLOOR,
    premium_max=PREMIUM_MAX,
    hour_to_bucket=None,
    resell_remaining_capacity=False,
):
    out = df.copy()

    # --- ID - DA spread and hour buckets -----------------------------------
    out["id_da_spread"] = out["ID-DA"]
    out["hour_bucket"] = assign_hour_bucket(out.index, hour_to_bucket=hour_to_bucket)
    out["day"] = out.index.normalize()

    # --- Raw ID premium -----------------------------------------------------
    daily = out.groupby(["day", "hour_bucket"])["id_da_spread"].mean()
    daily_wide = daily.unstack("hour_bucket").sort_index()
    premium_raw_wide = (
        daily_wide.rolling(window=x_days, min_periods=1)
        .max()
        .shift(1)
    )
    premium_raw = premium_raw_wide.stack().rename("id_premium_raw")
    out = out.join(premium_raw, on=["day", "hour_bucket"])

    # --- Premium final ------------------------------------------------------
    out["id_premium_min"] = float(premium_floor)
    out["id_premium"] = out["id_premium_raw"].clip(
        lower=out["id_premium_min"], upper=premium_max
    )

    # --- Volume split -------------------------------------------------------
    out["id_factor"] = p_factor
    out["vol_da_leg"] = out[VOL_COL] * (1 - out["id_factor"])
    out["vol_id_leg"] = out[VOL_COL] * out["id_factor"]

    # --- Prices used for bids ----------------------------------------------
    out["id_offer_price"] = out["id_premium"].fillna(0.0) + out[PRICE_COL]

    # DA leg accepted if P_t <= DA
    da_accepted = out[PRICE_COL] <= out[DA_COL]
    out["pnl_da_leg_simple"] = np.where(da_accepted, out["vol_da_leg"] * out[DA_COL], 0.0)

    # ID leg accepted if (id_premium + P_t) <= DA
    id_accepted = out["id_offer_price"] <= out[DA_COL]
    out["pnl_id_leg_simple"] = np.where(
        id_accepted, out["vol_id_leg"] * out[DA_COL], 0.0
    )

    # Remaining capacity (not accepted on ID leg)
    out["remaining_capacity"] = np.where(~id_accepted, out["vol_id_leg"], 0.0)

    if resell_remaining_capacity:
        resell_ok = out["id_offer_price"] <= out[ID_COL]
        out["pnl_resell_simple"] = np.where(
            resell_ok, out["remaining_capacity"] * out["id_offer_price"], 0.0
        )
    else:
        out["pnl_resell_simple"] = 0.0

    out["pnl_strategy_simple"] = (
        out["pnl_da_leg_simple"] + out["pnl_id_leg_simple"] + out["pnl_resell_simple"]
    )

    return out[["pnl_strategy_simple"]]

In [38]:
#NEW
# --- Grid search sur TRAIN ---
X_DAYS_GRID = [1, 2, 3, 5, 7]
PREMIUM_FLOOR_GRID = [-20, -10, 0, 10, 20]
PREMIUM_MAX_GRID = [150, 250, 400, 600]
N_BUCKETS_GRID = [3, 4, 5, 6, 24]

search_rows = []

for n_buckets in N_BUCKETS_GRID:
    hour_map = build_hour_bucket_map(df_train, n_buckets=n_buckets, spread_col="ID-DA")

    for x_days, p_floor, p_max in product(X_DAYS_GRID, PREMIUM_FLOOR_GRID, PREMIUM_MAX_GRID):
        if p_floor > p_max:
            continue

        pnl_train = compute_pnl(
            df_train,
            x_days=x_days,
            premium_floor=p_floor,
            premium_max=p_max,
            hour_to_bucket=hour_map,
            resell_remaining_capacity=True,
        )["pnl_strategy_simple"].sum()

        search_rows.append({
            "train_pnl": pnl_train,
            "n_buckets": n_buckets,
            "x_days": x_days,
            "premium_floor": p_floor,
            "premium_max": p_max,
            "hour_map": hour_map,
        })

search_df = pd.DataFrame(search_rows).sort_values("train_pnl", ascending=False).reset_index(drop=True)
best = search_df.iloc[0]

best_params = {
    "n_buckets": int(best["n_buckets"]),
    "x_days": int(best["x_days"]),
    "premium_floor": float(best["premium_floor"]),
    "premium_max": float(best["premium_max"]),
}
best_hour_bucket_map = best["hour_map"]

print("Best params (train):", best_params)
print("Best train PnL:", round(float(best["train_pnl"]), 2))
search_df.head(10)

Best params (train): {'n_buckets': 3, 'x_days': 1, 'premium_floor': -20.0, 'premium_max': 150.0}
Best train PnL: 2103959.07

,train_pnl,n_buckets,x_days,premium_floor,premium_max,hour_map
0,2.103959e+06,3,1,-20,150,"{0: 'bucket_2', 1: 'bucket_2', 2: 'bucket_2', ..."
1,2.103959e+06,3,1,-20,250,"{0: 'bucket_2', 1: 'bucket_2', 2: 'bucket_2', ..."
2,2.103959e+06,3,1,-20,400,"{0: 'bucket_2', 1: 'bucket_2', 2: 'bucket_2', ..."
3,2.103959e+06,3,1,-20,600,"{0: 'bucket_2', 1: 'bucket_2', 2: 'bucket_2', ..."
4,2.103708e+06,3,1,-10,600,"{0: 'bucket_2', 1: 'bucket_2', 2: 'bucket_2', ..."
5,2.103708e+06,3,1,-10,400,"{0: 'bucket_2', 1: 'bucket_2', 2: 'bucket_2', ..."
6,2.103708e+06,3,1,-10,250,"{0: 'bucket_2', 1: 'bucket_2', 2: 'bucket_2', ..."
7,2.103708e+06,3,1,-10,150,"{0: 'bucket_2', 1: 'bucket_2', 2: 'bucket_2', ..."
8,2.103484e+06,6,1,-20,150,"{0: 'bucket_4', 1: 'bucket_5', 2: 'bucket_5', ..."
9,2.103484e+06,6,1,-20,250,"{0: 'bucket_4', 1: 'bucket_5', 2: 'bucket_5', ..."

In [39]:
best_hour_bucket_map

{0: 'bucket_2',
 1: 'bucket_2',
 2: 'bucket_2',
 3: 'bucket_0',
 4: 'bucket_0',
 5: 'bucket_1',
 6: 'bucket_0',
 7: 'bucket_0',
 8: 'bucket_1',
 9: 'bucket_1',
 10: 'bucket_0',
 11: 'bucket_0',
 12: 'bucket_0',
 13: 'bucket_1',
 14: 'bucket_2',
 15: 'bucket_1',
 16: 'bucket_2',
 17: 'bucket_2',
 18: 'bucket_2',
 19: 'bucket_2',
 20: 'bucket_1',
 21: 'bucket_0',
 22: 'bucket_1',
 23: 'bucket_1'}

In [40]:
# --- Evaluation finale sur TEST avec les meilleurs paramètres ---
df_pnl = pd.DataFrame(index=df_test.index)
df_pnl["pnl_strategy_simple"] = compute_pnl(
    df_test,
    x_days=best_params["x_days"],
    premium_floor=best_params["premium_floor"],
    premium_max=best_params["premium_max"],
    hour_to_bucket=best_hour_bucket_map,
    resell_remaining_capacity=True,
)["pnl_strategy_simple"]

df_pnl

                           pnl_strategy_simple
datetime
2026-03-16 00:00:00+00:00               0.0000
2026-03-16 01:00:00+00:00               0.0000
2026-03-16 02:00:00+00:00               0.0000
2026-03-16 03:00:00+00:00               0.0000
2026-03-16 04:00:00+00:00               0.0000
...                                        ...
2026-04-26 20:00:00+00:00             855.6975
2026-04-26 21:00:00+00:00             736.2000
2026-04-26 22:00:00+00:00             446.9850
2026-04-26 23:00:00+00:00             388.0350
2026-04-27 00:00:00+00:00             365.5800

[1009 rows x 1 columns]

## PnL - Benchmark strategy

In [41]:
def compute_base_pnl(
    df,
    vol_col=VOL_COL,
    price_col=PRICE_COL,
    da_col=DA_COL,
    id_col=ID_COL,
    sell_remaining_if_da_le_id=False,
):
    out = df.copy()

    # Acceptation DA : bid price <= DA
    da_accepted = out[price_col] <= out[da_col]

    # PnL base : si accepté, gain = DA * VOL, sinon 0
    out["pnl_base_benchmark"] = np.where(da_accepted, out[da_col] * out[vol_col], 0.0)

    # Volume restant (non vendu en base)
    out["remaining_volume"] = np.where(da_accepted, 0.0, out[vol_col])

    # Option : vendre le volume restant si DA <= ID
    if sell_remaining_if_da_le_id:
        can_sell_remaining = out[price_col] <= out[id_col]
        out["pnl_remaining_benchmark"] = np.where(
            can_sell_remaining,
            out["remaining_volume"] * out[price_col],
            0.0,
        )
    else:
        out["pnl_remaining_benchmark"] = 0.0

    out["pnl_total_benchmark"] = out["pnl_base_benchmark"] + out["pnl_remaining_benchmark"]

    return out["pnl_total_benchmark"]

In [42]:
df_pnl["pnl_total_benchmark"] = compute_base_pnl(df_test)
df_pnl

                           pnl_strategy_simple  pnl_total_benchmark
datetime
2026-03-16 00:00:00+00:00               0.0000               0.0000
2026-03-16 01:00:00+00:00               0.0000               0.0000
2026-03-16 02:00:00+00:00               0.0000               0.0000
2026-03-16 03:00:00+00:00               0.0000               0.0000
2026-03-16 04:00:00+00:00               0.0000               0.0000
...                                        ...                  ...
2026-04-26 20:00:00+00:00             855.6975             855.6975
2026-04-26 21:00:00+00:00             736.2000             736.2000
2026-04-26 22:00:00+00:00             446.9850             446.9850
2026-04-26 23:00:00+00:00             388.0350             388.0350
2026-04-27 00:00:00+00:00             365.5800             365.5800

[1009 rows x 2 columns]

In [43]:
df_basic_strat.loc["2025-10-18 00:00:00+00:00":"2025-10-27 23:00:00+00:00"]

,id_vwap_fr,da_actual_price,biomass_storm_fct,blast_gas_storm_fct,coal_storm_fct,free_fuel_storm_fct,hydro_storm_fct,nat_gas_storm_fct,nuclear_storm_fct,pump_storm_fct,...,da_storm_de_fct,da_storm_fr_fct,da_storm_be_fct,da_storm_ch_fct,da_storm_uk_fct,da_storm_es_fct,da_storm_it_fct,ID-DA,P_t,P_max
datetime,,,,,,,,,,,,,,,,,,,,,
2025-10-18 00:00:00+00:00,70.906955,90.230090,170.0,0.0,0.0,1300.0,3742.515004,3562.709590,41114.3226,0.000000,...,96.477323,90.232498,94.566593,96.989958,92.308083,104.280716,117.014972,-19.323135,1.46,9.0
2025-10-18 01:00:00+00:00,72.829672,82.637583,170.0,0.0,0.0,1300.0,3742.515004,2308.292901,41114.3226,0.000000,...,96.326916,84.801344,92.823936,97.265877,89.873013,105.970619,118.006734,-9.807910,1.46,9.0
2025-10-18 02:00:00+00:00,70.769720,74.880075,170.0,0.0,0.0,1300.0,3742.515004,2308.292901,41114.3226,0.000000,...,94.947788,81.809447,90.926939,96.026553,86.702181,106.254353,104.667129,-4.110355,1.46,9.0
2025-10-18 03:00:00+00:00,75.176107,78.867579,170.0,0.0,0.0,1300.0,3742.515004,2308.292901,41541.5137,0.000000,...,95.622881,80.350442,90.958058,96.873269,85.155919,111.799672,106.458079,-3.691472,1.46,9.0
2025-10-18 04:00:00+00:00,77.433026,80.842581,170.0,0.0,0.0,1300.0,3742.515004,2308.292901,41968.7048,0.000000,...,101.866276,81.832155,89.563160,101.866276,86.726248,111.279899,120.931323,-3.409555,1.46,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-27 19:00:00+00:00,94.098868,99.217599,170.0,0.0,0.0,1300.0,7535.689880,1372.670126,43442.2741,2490.300000,...,67.720959,67.071109,80.885312,117.668239,95.727759,172.343625,145.363267,-5.118731,2.17,9.5
2025-10-27 20:00:00+00:00,71.392968,83.565084,170.0,0.0,0.0,1300.0,6535.689880,244.965335,43442.2741,1292.876430,...,63.085382,64.763624,72.109094,109.969924,82.369853,159.269477,129.709086,-12.172116,2.17,9.5
2025-10-27 21:00:00+00:00,75.690650,79.292579,170.0,0.0,0.0,1300.0,6535.689880,244.965335,43442.2741,996.215286,...,50.646496,65.220745,65.220745,95.077359,74.923241,122.061311,115.199676,-3.601930,2.17,9.5
2025-10-27 22:00:00+00:00,60.547288,67.260067,170.0,0.0,0.0,1300.0,6535.689880,244.965335,43442.2741,692.931795,...,39.177649,53.225284,53.225284,88.530628,56.408500,109.743325,105.473809,-6.712779,2.17,9.5
2025-10-27 23:00:00+00:00,39.220423,48.510000,170.0,0.0,0.0,1300.0,6015.463697,244.965335,41982.1298,-1367.458477,...,24.056523,38.336840,38.450563,86.175939,36.173435,112.166409,86.175939,-9.289577,2.17,9.5

In [44]:
# PnL summary
print("Strategy PnL :", round(df_pnl["pnl_strategy_simple"].sum(), 2))
gain_pct = (df_pnl["pnl_strategy_simple"].sum() - df_pnl["pnl_total_benchmark"].sum()) / np.abs(df_pnl["pnl_total_benchmark"].sum()) * 100
print(f"Relative gain: {gain_pct:.2f} %")

Strategy PnL : 319333.34
Relative gain: 1.75 %

In [45]:
# Cumulative PnL plot
df_plot = df_pnl[["pnl_strategy_simple", "pnl_total_benchmark"]].cumsum().reset_index()
fig = px.line(df_plot, x="datetime", y=["pnl_strategy_simple", "pnl_total_benchmark"],
              labels={"value": "Cumulative PnL (EUR)", "variable": "Strategy"},
              title="Cumulative PnL: normal vs ID premium")
fig.show()